#!/bin/bash
#set -x
echo "this is a program to print the multiple of 3 and 5 uptil 1000"

count=1
while [ $count -le 10 ]; do
	if [ $((count % 3)) -eq 0 ] || [ $((count % 5)) -eq 0 ]; then
		echo $count
	fi
	count=$((count + 1))
done
