#!/bin/bash
echo "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
What is the smallest positive number that is evenly divisible divisible with no remainder by all of the numbers from 1 to 20"
number=20
flag=1
while [ $flag -le 20 ]; do
    flag=1
    for i in {2..20}; do
        # echo $i
        if [ $((number % i)) -eq 0 ]; then
            flag=$((flag + 1))
        fi
    done
    # echo $flag
    if [ $flag -eq 20 ]; then
        break
    fi
    number=$((number + 1))
    echo $number
done
# echo $number
